deployment:
  imageVersion: 2.0.0
hpa:
  minReplicas: 1
  maxReplicas: 5
  cpuUtilization: 5
config:
  nginxConfig: |
    events {}
    pid /tmp/nginx.pid;

    http {
        server {
            listen 80;

            location / {
                root /usr/share/nginx/html;
                index index.html;
            }

            location /api/ {
                proxy_pass http://backend:8080/;
            }
        }
    }
service:
  nodePort: 30080
